# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rJxRzbA5ioo-lQ_0EffvrqF9PYuvOGNJ
"""

from pandas import read_excel
from keras.models import Sequential
from keras.layers import Dense, activation
import numpy

dataset = read_excel("/content/Assignment 2_BUSI 651_House Prices.xlsx")
datalength = len(dataset)

x_data = dataset[["GarageCars","GarageArea","OverallQual","GrLivArea"]]
y_data = dataset["SalePrice"]

train_len=int(datalength*0.8)
x_train=x_data[:train_len+1]
y_train=y_data[:train_len+1]
x_test=x_data[train_len+1:]
y_test=y_data[train_len+1:]

price_model = Sequential()
price_model.add(Dense(64,activation = "relu",input_dim = 4)) #first hidden layer with 4 input
price_model.add(Dense(64,activation="relu"))#Second hidden layer
price_model.add(Dense(64,activation="relu"))#Third hidden layer
#price_model.add(Dense(64,activation="relu"))#fourth hidden layer
price_model.add(Dense(1))

price_model.compile(loss="mean_squared_error",optimizer="adam")
price_model.fit(x_train,y_train,epochs=1000)

y_test.shape

y_predict = price_model.predict(x_test)
y_predict.shape

y_predict_1 = y_predict.reshape(1,291)

y_test_1 = y_test.to_numpy()

APE = abs(numpy.subtract(y_predict_1,y_test_1))/y_test_1*100

MAPE = numpy.mean(APE)
MAPE

price_model.predict([[2,600,7,2200]])